# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_igpdialog.ui'
#
# Created: Fri Jun 20 12:17:47 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_IGPDialog(object):
    def setupUi(self, IGPDialog):
        IGPDialog.setObjectName(_fromUtf8("IGPDialog"))
        IGPDialog.setWindowModality(QtCore.Qt.WindowModal)
        IGPDialog.resize(481, 512)
        self.tabWidget = QtGui.QTabWidget(IGPDialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 5, 476, 501))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(476, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(476, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab003 = QtGui.QWidget()
        self.tab003.setObjectName(_fromUtf8("tab003"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab003)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(5, 5, 461, 456))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtCoord = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txtCoord.setObjectName(_fromUtf8("txtCoord"))
        self.gridLayout.addWidget(self.txtCoord, 1, 1, 1, 2)
        self.lblCoord = QtGui.QLabel(self.gridLayoutWidget)
        self.lblCoord.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCoord.setObjectName(_fromUtf8("lblCoord"))
        self.gridLayout.addWidget(self.lblCoord, 1, 0, 1, 1)
        self.btnPasteCoord = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnPasteCoord.setAutoDefault(False)
        self.btnPasteCoord.setObjectName(_fromUtf8("btnPasteCoord"))
        self.gridLayout.addWidget(self.btnPasteCoord, 1, 3, 1, 1)
        self.lblCoord_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.lblCoord_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCoord_2.setObjectName(_fromUtf8("lblCoord_2"))
        self.gridLayout.addWidget(self.lblCoord_2, 3, 0, 1, 1)
        self.txtResult = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtResult.setFont(font)
        self.txtResult.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.txtResult.setAlignment(QtCore.Qt.AlignCenter)
        self.txtResult.setObjectName(_fromUtf8("txtResult"))
        self.gridLayout.addWidget(self.txtResult, 3, 1, 1, 2)
        self.btnReport = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnReport.setAutoDefault(False)
        self.btnReport.setObjectName(_fromUtf8("btnReport"))
        self.gridLayout.addWidget(self.btnReport, 3, 3, 1, 1)
        self.btnIGP = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnIGP.setAutoDefault(True)
        self.btnIGP.setDefault(True)
        self.btnIGP.setObjectName(_fromUtf8("btnIGP"))
        self.gridLayout.addWidget(self.btnIGP, 2, 3, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setRowCount(11)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(9, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidget.setItem(10, 2, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 4)
        self.tabWidget.addTab(self.tab003, _fromUtf8(""))
        self.tab002 = QtGui.QWidget()
        self.tab002.setEnabled(True)
        self.tab002.setObjectName(_fromUtf8("tab002"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab002)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab002)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 252, 56))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioutm = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioutm.setObjectName(_fromUtf8("radioutm"))
        self.gridLayout_3.addWidget(self.radioutm, 1, 0, 1, 1)
        self.radiodms = QtGui.QRadioButton(self.layoutWidget_2)
        self.radiodms.setChecked(True)
        self.radiodms.setObjectName(_fromUtf8("radiodms"))
        self.gridLayout_3.addWidget(self.radiodms, 0, 0, 1, 1)
        self.radiodm = QtGui.QRadioButton(self.layoutWidget_2)
        self.radiodm.setObjectName(_fromUtf8("radiodm"))
        self.gridLayout_3.addWidget(self.radiodm, 0, 1, 1, 1)
        self.radiod = QtGui.QRadioButton(self.layoutWidget_2)
        self.radiod.setObjectName(_fromUtf8("radiod"))
        self.gridLayout_3.addWidget(self.radiod, 1, 1, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 55, 301, 136))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtCoordinates = QtGui.QLineEdit(self.layoutWidget)
        self.txtCoordinates.setObjectName(_fromUtf8("txtCoordinates"))
        self.gridLayout_2.addWidget(self.txtCoordinates, 0, 0, 1, 1)
        self.btnGet = QtGui.QPushButton(self.layoutWidget)
        self.btnGet.setObjectName(_fromUtf8("btnGet"))
        self.gridLayout_2.addWidget(self.btnGet, 3, 0, 1, 1)
        self.btnClipboard = QtGui.QPushButton(self.layoutWidget)
        self.btnClipboard.setObjectName(_fromUtf8("btnClipboard"))
        self.gridLayout_2.addWidget(self.btnClipboard, 2, 0, 1, 1)
        self.btnGo = QtGui.QPushButton(self.layoutWidget)
        self.btnGo.setObjectName(_fromUtf8("btnGo"))
        self.gridLayout_2.addWidget(self.btnGo, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tab002, _fromUtf8(""))
        self.tab001 = QtGui.QWidget()
        self.tab001.setEnabled(True)
        self.tab001.setMinimumSize(QtCore.QSize(472, 0))
        self.tab001.setObjectName(_fromUtf8("tab001"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab001)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.txtSearch = QtGui.QLineEdit(self.tab001)
        self.txtSearch.setObjectName(_fromUtf8("txtSearch"))
        self.verticalLayout.addWidget(self.txtSearch)
        self.chkBBOX = QtGui.QCheckBox(self.tab001)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBBOX.sizePolicy().hasHeightForWidth())
        self.chkBBOX.setSizePolicy(sizePolicy)
        self.chkBBOX.setObjectName(_fromUtf8("chkBBOX"))
        self.verticalLayout.addWidget(self.chkBBOX)
        self.tblResult = QtGui.QTableWidget(self.tab001)
        self.tblResult.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblResult.sizePolicy().hasHeightForWidth())
        self.tblResult.setSizePolicy(sizePolicy)
        self.tblResult.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblResult.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblResult.setShowGrid(True)
        self.tblResult.setColumnCount(3)
        self.tblResult.setObjectName(_fromUtf8("tblResult"))
        self.tblResult.setRowCount(0)
        self.verticalLayout.addWidget(self.tblResult)
        self.lblResult = QtGui.QLabel(self.tab001)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.verticalLayout.addWidget(self.lblResult)
        self.tabWidget.addTab(self.tab001, _fromUtf8(""))

        self.retranslateUi(IGPDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IGPDialog)
        IGPDialog.setTabOrder(self.tabWidget, self.txtCoord)
        IGPDialog.setTabOrder(self.txtCoord, self.btnPasteCoord)
        IGPDialog.setTabOrder(self.btnPasteCoord, self.txtResult)
        IGPDialog.setTabOrder(self.txtResult, self.btnReport)
        IGPDialog.setTabOrder(self.btnReport, self.radiod)
        IGPDialog.setTabOrder(self.radiod, self.radioutm)
        IGPDialog.setTabOrder(self.radioutm, self.radiodm)
        IGPDialog.setTabOrder(self.radiodm, self.txtCoordinates)
        IGPDialog.setTabOrder(self.txtCoordinates, self.btnGet)
        IGPDialog.setTabOrder(self.btnGet, self.btnClipboard)
        IGPDialog.setTabOrder(self.btnClipboard, self.btnGo)
        IGPDialog.setTabOrder(self.btnGo, self.txtSearch)
        IGPDialog.setTabOrder(self.txtSearch, self.chkBBOX)
        IGPDialog.setTabOrder(self.chkBBOX, self.tblResult)
        IGPDialog.setTabOrder(self.tblResult, self.radiodms)

    def retranslateUi(self, IGPDialog):
        IGPDialog.setWindowTitle(QtGui.QApplication.translate("IGPDialog", "IGP - Índice de gravedad potencial", None, QtGui.QApplication.UnicodeUTF8))
        self.txtCoord.setText(QtGui.QApplication.translate("IGPDialog", "458233.02, 3110465.86", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCoord.setText(QtGui.QApplication.translate("IGPDialog", "Coordenadas", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPasteCoord.setText(QtGui.QApplication.translate("IGPDialog", "Pegar", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCoord_2.setText(QtGui.QApplication.translate("IGPDialog", "Resultado", None, QtGui.QApplication.UnicodeUTF8))
        self.txtResult.setText(QtGui.QApplication.translate("IGPDialog", "29 - ALTA", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReport.setText(QtGui.QApplication.translate("IGPDialog", "Informe PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIGP.setText(QtGui.QApplication.translate("IGPDialog", "Calcular IGP", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "PENDIENTE", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "ACCESIBILIDAD", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "COMBUSTIBILIDAD", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("IGPDialog", "CONTINUIDAD", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("IGPDialog", "VEL. VIENTO", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("IGPDialog", "TEMPERATURA", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("IGPDialog", "E.D.E.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("IGPDialog", "I.I.E.R.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("IGPDialog", "EVACUACIÓN POB.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("IGPDialog", "PATRIMONIO HIST.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("IGPDialog", "VALOR ECOLÓGICO", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "VALOR", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "SIGNIFICADO", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "PUNTUACIÓN", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "19", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(0, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Pte. suave", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(0, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(1, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "MEDIA", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(1, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Por viales y/o ...", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(1, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(2, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(2, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Alta", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(2, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(3, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "40", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(3, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Nivel 2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(3, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(4, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(4, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Baja", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(4, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(5, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "40", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(5, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Baja", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(5, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(6, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "NO", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(6, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Ausencia", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(7, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "SI", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(7, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Presencia i.i.e.r.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(7, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(8, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "SI", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(8, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Necesaria evac.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(8, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(9, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "SI", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(9, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "Presencia patr.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(9, 2)
        item.setText(QtGui.QApplication.translate("IGPDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(10, 0)
        item.setText(QtGui.QApplication.translate("IGPDialog", "NO", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.item(10, 1)
        item.setText(QtGui.QApplication.translate("IGPDialog", "No hay afección", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab003), QtGui.QApplication.translate("IGPDialog", "IGP", None, QtGui.QApplication.UnicodeUTF8))
        self.radioutm.setText(QtGui.QApplication.translate("IGPDialog", "UTM", None, QtGui.QApplication.UnicodeUTF8))
        self.radiodms.setText(QtGui.QApplication.translate("IGPDialog", "Grad. Min. Seg.", None, QtGui.QApplication.UnicodeUTF8))
        self.radiodm.setText(QtGui.QApplication.translate("IGPDialog", "Grad. Min.", None, QtGui.QApplication.UnicodeUTF8))
        self.radiod.setText(QtGui.QApplication.translate("IGPDialog", "Grados", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGet.setText(QtGui.QApplication.translate("IGPDialog", "Empezar captura", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClipboard.setText(QtGui.QApplication.translate("IGPDialog", "Copiar al portapapeles", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGo.setText(QtGui.QApplication.translate("IGPDialog", "Ir", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab002), QtGui.QApplication.translate("IGPDialog", "Coordenadas", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBBOX.setText(QtGui.QApplication.translate("IGPDialog", "Limitar la búsqueda a la extensión actual", None, QtGui.QApplication.UnicodeUTF8))
        self.lblResult.setText(QtGui.QApplication.translate("IGPDialog", "Encontrado (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab001), QtGui.QApplication.translate("IGPDialog", "Lugar", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
